### ISSUE TITLE
Incomplete print

### ISSUE THREAD

**Issue by leonardovargasleffa** [Klemen1337/node-thermal-printer#149]
I using module "node-thermal-printer" to create buffer and this for send data to print with node-printer.

![](https://user-images.githubusercontent.com/5497003/86427514-bbe04000-bcc0-11ea-85d6-60ca3742ef8b.png)

But sometimes, part of the beginning of the text is not printed.
I save text in one file and save full text in file normally, but not printed full text.

Examples of buffer string

Print complete:
[5efd1b5d515e0996582c288a](https://github.com/thiagoelg/node-printer/files/4867561/5efd1b5d515e0996582c288a.txt)

Print incomplete:
[5efd152cc5804c81f94db8b3](https://github.com/thiagoelg/node-printer/files/4867562/5efd152cc5804c81f94db8b3.txt)
This cut the first 5 lines.

This not appear on second print.
![](https://user-images.githubusercontent.com/5497003/86427981-04e4c400-bcc2-11ea-94b0-4f15213ad360.png)

**Comment by samuelcseto** [comment]
Hello! I would have to see the whole code including the part where the print gets executed. Everything on your screenshot looks alright so the issue has to be somewhere else.

**Comment by asaadbaw** [comment]
Hello

I had this issue too. I discovered that the printer object gets destroyed before the printing finish.

![image](https://user-images.githubusercontent.com/8416276/97101140-cc6f5880-16ab-11eb-8461-c4e656af5042.png)

**Comment by jortegamo** [comment]
Hi, I am facing the same issue but I am using the File interface. I mean, I am using the device path interface as Interface parameter. I have discovered that is due to the buffer size. I create all printing commands and then invoke to the execute method. The printer is printing only a certain data contained into the buffer. If I rerun the execute command then the printer prints part from the remaining data. 

I guess that all the buffer is send to the printer but it is not able to print the entire buffer at once. 

I am using an EPSON TM - t88iv. Maybe there ir any parameter into options to solve this problem? or maybe is an specific printer configuration? 

As a workaround I am using the .raw() method to print instantly and printer.clear() and several printer.execute() for each line. But I think that is not the optimal solution for this. 

Could me give me support about this? 

thanks a lot!
